name: Scrape Mensaar Daily

on:
  schedule:
  # this is UTC not current timezone!!!!!
    - cron: '0 13 * * 1-5'  # Runs at 2 PM UTC, Monday to Friday

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager pytz

    - name: Run scraping script
      run: |
        python Mensaar_scraper.py  

    # Save meal_component_counts.json and the dynamic menu_<date>.json
    - name: Upload meal component counts
      uses: actions/upload-artifact@v3
      with:
        name: meal_component_counts
        path: output/meal_component_counts.json

    - name: Upload today's menu
      uses: actions/upload-artifact@v3
      with:
        name: menu_json
        path: output/menu_*.json 
